### Exercici 1

In [20]:
import numpy as np
from numpy import random

matriu = np.array(random.randint(100, size=(8)), dtype = "i8")
print(matriu, matriu.dtype)
print("Dimensió:", matriu.ndim)
print("Forma:", matriu.shape)

[34 99 33 21 62  5 53 61] int64
Dimensió: 1
Forma: (8,)


### Exercici 2

In [22]:
sumatori = 0
for i in matriu:
    sumatori += i
mitja = sumatori/len(matriu)
print(mitja)

46.0


### Exercici 3

In [34]:
x=random.randint(100, size=(5,5))
print(x)

[[43 12  3 73 16]
 [29 81 44 60 54]
 [ 0 57 63 92 78]
 [18 11 39 50 34]
 [90 77 28 74 14]]


In [32]:
maxim = 0
for i in x:
    for j in i:
        if j>maxim:
            maxim=j
print("Valor màxim de la matriu:",maxim)

maxEix0 = np.amax(x,0)
print("Valor màxim de l'eix 0:",maxEix0)
maxEix1 = np.amax(x,1)
print("Valor màxim de l'eix 1:",maxEix1)

Valor màxim de la matriu: 99
Valor màxim de l'eix 0: [77 90 84 99 98]
Valor màxim de l'eix 1: [99 98 73 81 90]
